//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicServerSide
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicTemplateAttribute
    {
        public int TemplateId { get; set; }
        public int AttributeId { get; set; }
        public string DisplayName { get; set; }
        public int TypeId { get; set; }
        public int Idx { get; set; }
    
        public virtual DynamicAttribute DynamicAttribute { get; set; }
        public virtual DynamicTemplate DynamicTemplate { get; set; }
        public virtual DynamicType DynamicType { get; set; }
    }
}
