//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicServerSide
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DynamicEntities : DbContext
    {
        public DynamicEntities()
            : base("name=DynamicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DynamicAttribute> DynamicAttributes { get; set; }
        public virtual DbSet<DynamicTemplate> DynamicTemplates { get; set; }
        public virtual DbSet<DynamicTemplateAttribute> DynamicTemplateAttributes { get; set; }
        public virtual DbSet<DynamicType> DynamicTypes { get; set; }
    }
}
