//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: dynamicmetadataservice.cs
// Generation date: 1/5/2019 9:08:30 PM
namespace DynamicClient
{
    
    /// <summary>
    /// There are no comments for DynamicEntities in the schema.
    /// </summary>
    public partial class DynamicEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DynamicEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for DynamicAttributes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicAttribute> DynamicAttributes
        {
            get
            {
                if ((this._DynamicAttributes == null))
                {
                    this._DynamicAttributes = base.CreateQuery<DynamicAttribute>("DynamicAttributes");
                }
                return this._DynamicAttributes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicAttribute> _DynamicAttributes;
        /// <summary>
        /// There are no comments for DynamicTemplates in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicTemplate> DynamicTemplates
        {
            get
            {
                if ((this._DynamicTemplates == null))
                {
                    this._DynamicTemplates = base.CreateQuery<DynamicTemplate>("DynamicTemplates");
                }
                return this._DynamicTemplates;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicTemplate> _DynamicTemplates;
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicTemplateAttribute> DynamicTemplateAttributes
        {
            get
            {
                if ((this._DynamicTemplateAttributes == null))
                {
                    this._DynamicTemplateAttributes = base.CreateQuery<DynamicTemplateAttribute>("DynamicTemplateAttributes");
                }
                return this._DynamicTemplateAttributes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicTemplateAttribute> _DynamicTemplateAttributes;
        /// <summary>
        /// There are no comments for DynamicTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicType> DynamicTypes
        {
            get
            {
                if ((this._DynamicTypes == null))
                {
                    this._DynamicTypes = base.CreateQuery<DynamicType>("DynamicTypes");
                }
                return this._DynamicTypes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicType> _DynamicTypes;
        /// <summary>
        /// There are no comments for DynamicAttributes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicAttributes(DynamicAttribute dynamicAttribute)
        {
            base.AddObject("DynamicAttributes", dynamicAttribute);
        }
        /// <summary>
        /// There are no comments for DynamicTemplates in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicTemplates(DynamicTemplate dynamicTemplate)
        {
            base.AddObject("DynamicTemplates", dynamicTemplate);
        }
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicTemplateAttributes(DynamicTemplateAttribute dynamicTemplateAttribute)
        {
            base.AddObject("DynamicTemplateAttributes", dynamicTemplateAttribute);
        }
        /// <summary>
        /// There are no comments for DynamicTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicTypes(DynamicType dynamicType)
        {
            base.AddObject("DynamicTypes", dynamicType);
        }
    }
    /// <summary>
    /// There are no comments for DynamicModel.DynamicAttribute in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DynamicAttribute
    {
        /// <summary>
        /// Create a new DynamicAttribute object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicAttribute CreateDynamicAttribute(int ID, string name)
        {
            DynamicAttribute dynamicAttribute = new DynamicAttribute();
            dynamicAttribute.Id = ID;
            dynamicAttribute.Name = name;
            return dynamicAttribute;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute> DynamicTemplateAttributes
        {
            get
            {
                return this._DynamicTemplateAttributes;
            }
            set
            {
                if ((value != null))
                {
                    this._DynamicTemplateAttributes = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute> _DynamicTemplateAttributes = new global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute>();
    }
    /// <summary>
    /// There are no comments for DynamicModel.DynamicTemplate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DynamicTemplate
    {
        /// <summary>
        /// Create a new DynamicTemplate object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="isExist">Initial value of IsExist.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicTemplate CreateDynamicTemplate(int ID, string name, string description, int isExist)
        {
            DynamicTemplate dynamicTemplate = new DynamicTemplate();
            dynamicTemplate.Id = ID;
            dynamicTemplate.Name = name;
            dynamicTemplate.Description = description;
            dynamicTemplate.IsExist = isExist;
            return dynamicTemplate;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsExist in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IsExist
        {
            get
            {
                return this._IsExist;
            }
            set
            {
                this.OnIsExistChanging(value);
                this._IsExist = value;
                this.OnIsExistChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IsExist;
        partial void OnIsExistChanging(int value);
        partial void OnIsExistChanged();
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute> DynamicTemplateAttributes
        {
            get
            {
                return this._DynamicTemplateAttributes;
            }
            set
            {
                if ((value != null))
                {
                    this._DynamicTemplateAttributes = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute> _DynamicTemplateAttributes = new global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute>();
    }
    /// <summary>
    /// There are no comments for DynamicModel.DynamicTemplateAttribute in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AttributeId
    /// TemplateId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AttributeId", "TemplateId")]
    public partial class DynamicTemplateAttribute
    {
        /// <summary>
        /// Create a new DynamicTemplateAttribute object.
        /// </summary>
        /// <param name="templateId">Initial value of TemplateId.</param>
        /// <param name="attributeId">Initial value of AttributeId.</param>
        /// <param name="displayName">Initial value of DisplayName.</param>
        /// <param name="typeId">Initial value of TypeId.</param>
        /// <param name="idx">Initial value of Idx.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicTemplateAttribute CreateDynamicTemplateAttribute(int templateId, int attributeId, string displayName, int typeId, int idx)
        {
            DynamicTemplateAttribute dynamicTemplateAttribute = new DynamicTemplateAttribute();
            dynamicTemplateAttribute.TemplateId = templateId;
            dynamicTemplateAttribute.AttributeId = attributeId;
            dynamicTemplateAttribute.DisplayName = displayName;
            dynamicTemplateAttribute.TypeId = typeId;
            dynamicTemplateAttribute.Idx = idx;
            return dynamicTemplateAttribute;
        }
        /// <summary>
        /// There are no comments for Property TemplateId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TemplateId
        {
            get
            {
                return this._TemplateId;
            }
            set
            {
                this.OnTemplateIdChanging(value);
                this._TemplateId = value;
                this.OnTemplateIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TemplateId;
        partial void OnTemplateIdChanging(int value);
        partial void OnTemplateIdChanged();
        /// <summary>
        /// There are no comments for Property AttributeId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AttributeId
        {
            get
            {
                return this._AttributeId;
            }
            set
            {
                this.OnAttributeIdChanging(value);
                this._AttributeId = value;
                this.OnAttributeIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AttributeId;
        partial void OnAttributeIdChanging(int value);
        partial void OnAttributeIdChanged();
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property TypeId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TypeId
        {
            get
            {
                return this._TypeId;
            }
            set
            {
                this.OnTypeIdChanging(value);
                this._TypeId = value;
                this.OnTypeIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TypeId;
        partial void OnTypeIdChanging(int value);
        partial void OnTypeIdChanged();
        /// <summary>
        /// There are no comments for Property Idx in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Idx
        {
            get
            {
                return this._Idx;
            }
            set
            {
                this.OnIdxChanging(value);
                this._Idx = value;
                this.OnIdxChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Idx;
        partial void OnIdxChanging(int value);
        partial void OnIdxChanged();
        /// <summary>
        /// There are no comments for DynamicAttribute in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicAttribute DynamicAttribute
        {
            get
            {
                return this._DynamicAttribute;
            }
            set
            {
                this._DynamicAttribute = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DynamicAttribute _DynamicAttribute;
        /// <summary>
        /// There are no comments for DynamicTemplate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicTemplate DynamicTemplate
        {
            get
            {
                return this._DynamicTemplate;
            }
            set
            {
                this._DynamicTemplate = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DynamicTemplate _DynamicTemplate;
        /// <summary>
        /// There are no comments for DynamicType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicType DynamicType
        {
            get
            {
                return this._DynamicType;
            }
            set
            {
                this._DynamicType = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DynamicType _DynamicType;
    }
    /// <summary>
    /// There are no comments for DynamicModel.DynamicType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DynamicType
    {
        /// <summary>
        /// Create a new DynamicType object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="sqlTypeEnumCode">Initial value of SqlTypeEnumCode.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicType CreateDynamicType(int ID, string name, int sqlTypeEnumCode)
        {
            DynamicType dynamicType = new DynamicType();
            dynamicType.Id = ID;
            dynamicType.Name = name;
            dynamicType.SqlTypeEnumCode = sqlTypeEnumCode;
            return dynamicType;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SqlTypeEnumCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SqlTypeEnumCode
        {
            get
            {
                return this._SqlTypeEnumCode;
            }
            set
            {
                this.OnSqlTypeEnumCodeChanging(value);
                this._SqlTypeEnumCode = value;
                this.OnSqlTypeEnumCodeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SqlTypeEnumCode;
        partial void OnSqlTypeEnumCodeChanging(int value);
        partial void OnSqlTypeEnumCodeChanged();
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute> DynamicTemplateAttributes
        {
            get
            {
                return this._DynamicTemplateAttributes;
            }
            set
            {
                if ((value != null))
                {
                    this._DynamicTemplateAttributes = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute> _DynamicTemplateAttributes = new global::System.Collections.ObjectModel.Collection<DynamicTemplateAttribute>();
    }
}
