//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2014-11-08 04:44:54 AM
namespace WebClient.MetadataService
{

    /// <summary>
    /// There are no comments for DynamicEntities in the schema.
    /// </summary>
    public partial class DynamicEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DynamicEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicEntities(global::System.Uri serviceRoot) :
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DynamicModel", "DynamicClient.MetadataService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("DynamicClient.MetadataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("DynamicModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for DynamicAttributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicAttribute> DynamicAttributes
        {
            get
            {
                if ((this._DynamicAttributes == null))
                {
                    this._DynamicAttributes = base.CreateQuery<DynamicAttribute>("DynamicAttributes");
                }
                return this._DynamicAttributes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicAttribute> _DynamicAttributes;
        /// <summary>
        /// There are no comments for DynamicTemplates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicTemplate> DynamicTemplates
        {
            get
            {
                if ((this._DynamicTemplates == null))
                {
                    this._DynamicTemplates = base.CreateQuery<DynamicTemplate>("DynamicTemplates");
                }
                return this._DynamicTemplates;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicTemplate> _DynamicTemplates;
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicTemplateAttribute> DynamicTemplateAttributes
        {
            get
            {
                if ((this._DynamicTemplateAttributes == null))
                {
                    this._DynamicTemplateAttributes = base.CreateQuery<DynamicTemplateAttribute>("DynamicTemplateAttributes");
                }
                return this._DynamicTemplateAttributes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicTemplateAttribute> _DynamicTemplateAttributes;
        /// <summary>
        /// There are no comments for DynamicTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicType> DynamicTypes
        {
            get
            {
                if ((this._DynamicTypes == null))
                {
                    this._DynamicTypes = base.CreateQuery<DynamicType>("DynamicTypes");
                }
                return this._DynamicTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicType> _DynamicTypes;
        /// <summary>
        /// There are no comments for DynamicAttributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicAttributes(DynamicAttribute dynamicAttribute)
        {
            base.AddObject("DynamicAttributes", dynamicAttribute);
        }
        /// <summary>
        /// There are no comments for DynamicTemplates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicTemplates(DynamicTemplate dynamicTemplate)
        {
            base.AddObject("DynamicTemplates", dynamicTemplate);
        }
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicTemplateAttributes(DynamicTemplateAttribute dynamicTemplateAttribute)
        {
            base.AddObject("DynamicTemplateAttributes", dynamicTemplateAttribute);
        }
        /// <summary>
        /// There are no comments for DynamicTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicTypes(DynamicType dynamicType)
        {
            base.AddObject("DynamicTypes", dynamicType);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"DynamicModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><E" +
                "ntityType Name=\"DynamicAttribute\"><Key><PropertyRef Name=\"Id\" /></Key><Property " +
                "Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" " +
                "xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property N" +
                "ame=\"Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\"" +
                " Unicode=\"true\" /><NavigationProperty Name=\"DynamicTemplateAttributes\" Relations" +
                "hip=\"DynamicModel.FK_DynamicTemplateAttributes_DynamicAttribute\" ToRole=\"Dynamic" +
                "TemplateAttributes\" FromRole=\"DynamicAttribute\" /></EntityType><EntityType Name=" +
                "\"DynamicTemplate\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"" +
                "Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http:/" +
                "/schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=" +
                "\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" " +
                "/><Property Name=\"Description\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\"" +
                " FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"DynamicTemplateA" +
                "ttributes\" Relationship=\"DynamicModel.FK_DynamicTemplateAttributes_DynamicTempla" +
                "te\" ToRole=\"DynamicTemplateAttributes\" FromRole=\"DynamicTemplate\" /></EntityType" +
                "><EntityType Name=\"DynamicTemplateAttribute\"><Key><PropertyRef Name=\"AttributeId" +
                "\" /><PropertyRef Name=\"TemplateId\" /></Key><Property Name=\"TemplateId\" Type=\"Edm" +
                ".Int32\" Nullable=\"false\" /><Property Name=\"AttributeId\" Type=\"Edm.Int32\" Nullabl" +
                "e=\"false\" /><Property Name=\"DisplayName\" Type=\"Edm.String\" Nullable=\"false\" MaxL" +
                "ength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"TypeId\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" /><Property Name=\"Idx\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><NavigationProperty Name=\"DynamicAttribute\" Relationship=\"DynamicModel.FK_D" +
                "ynamicTemplateAttributes_DynamicAttribute\" ToRole=\"DynamicAttribute\" FromRole=\"D" +
                "ynamicTemplateAttributes\" /><NavigationProperty Name=\"DynamicTemplate\" Relations" +
                "hip=\"DynamicModel.FK_DynamicTemplateAttributes_DynamicTemplate\" ToRole=\"DynamicT" +
                "emplate\" FromRole=\"DynamicTemplateAttributes\" /><NavigationProperty Name=\"Dynami" +
                "cType\" Relationship=\"DynamicModel.FK_DynamicTemplateAttributes_DynamicType\" ToRo" +
                "le=\"DynamicType\" FromRole=\"DynamicTemplateAttributes\" /></EntityType><EntityType" +
                " Name=\"DynamicType\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http" +
                "://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Typ" +
                "e=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true" +
                "\" /><NavigationProperty Name=\"DynamicTemplateAttributes\" Relationship=\"DynamicMo" +
                "del.FK_DynamicTemplateAttributes_DynamicType\" ToRole=\"DynamicTemplateAttributes\"" +
                " FromRole=\"DynamicType\" /></EntityType><Association Name=\"FK_DynamicTemplateAttr" +
                "ibutes_DynamicAttribute\"><End Type=\"DynamicModel.DynamicAttribute\" Role=\"Dynamic" +
                "Attribute\" Multiplicity=\"1\" /><End Type=\"DynamicModel.DynamicTemplateAttribute\" " +
                "Role=\"DynamicTemplateAttributes\" Multiplicity=\"*\" /><ReferentialConstraint><Prin" +
                "cipal Role=\"DynamicAttribute\"><PropertyRef Name=\"Id\" /></Principal><Dependent Ro" +
                "le=\"DynamicTemplateAttributes\"><PropertyRef Name=\"AttributeId\" /></Dependent></R" +
                "eferentialConstraint></Association><Association Name=\"FK_DynamicTemplateAttribut" +
                "es_DynamicTemplate\"><End Type=\"DynamicModel.DynamicTemplate\" Role=\"DynamicTempla" +
                "te\" Multiplicity=\"1\" /><End Type=\"DynamicModel.DynamicTemplateAttribute\" Role=\"D" +
                "ynamicTemplateAttributes\" Multiplicity=\"*\" /><ReferentialConstraint><Principal R" +
                "ole=\"DynamicTemplate\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Dyna" +
                "micTemplateAttributes\"><PropertyRef Name=\"TemplateId\" /></Dependent></Referentia" +
                "lConstraint></Association><Association Name=\"FK_DynamicTemplateAttributes_Dynami" +
                "cType\"><End Type=\"DynamicModel.DynamicType\" Role=\"DynamicType\" Multiplicity=\"1\" " +
                "/><End Type=\"DynamicModel.DynamicTemplateAttribute\" Role=\"DynamicTemplateAttribu" +
                "tes\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"DynamicType\"><Pr" +
                "opertyRef Name=\"Id\" /></Principal><Dependent Role=\"DynamicTemplateAttributes\"><P" +
                "ropertyRef Name=\"TypeId\" /></Dependent></ReferentialConstraint></Association></S" +
                "chema><Schema Namespace=\"DynamicServerSide\" xmlns=\"http://schemas.microsoft.com/" +
                "ado/2009/11/edm\"><EntityContainer Name=\"DynamicEntities\" m:IsDefaultEntityContai" +
                "ner=\"true\"><EntitySet Name=\"DynamicAttributes\" EntityType=\"DynamicModel.DynamicA" +
                "ttribute\" /><EntitySet Name=\"DynamicTemplates\" EntityType=\"DynamicModel.DynamicT" +
                "emplate\" /><EntitySet Name=\"DynamicTemplateAttributes\" EntityType=\"DynamicModel." +
                "DynamicTemplateAttribute\" /><EntitySet Name=\"DynamicTypes\" EntityType=\"DynamicMo" +
                "del.DynamicType\" /><AssociationSet Name=\"FK_DynamicTemplateAttributes_DynamicAtt" +
                "ribute\" Association=\"DynamicModel.FK_DynamicTemplateAttributes_DynamicAttribute\"" +
                "><End Role=\"DynamicAttribute\" EntitySet=\"DynamicAttributes\" /><End Role=\"Dynamic" +
                "TemplateAttributes\" EntitySet=\"DynamicTemplateAttributes\" /></AssociationSet><As" +
                "sociationSet Name=\"FK_DynamicTemplateAttributes_DynamicTemplate\" Association=\"Dy" +
                "namicModel.FK_DynamicTemplateAttributes_DynamicTemplate\"><End Role=\"DynamicTempl" +
                "ate\" EntitySet=\"DynamicTemplates\" /><End Role=\"DynamicTemplateAttributes\" Entity" +
                "Set=\"DynamicTemplateAttributes\" /></AssociationSet><AssociationSet Name=\"FK_Dyna" +
                "micTemplateAttributes_DynamicType\" Association=\"DynamicModel.FK_DynamicTemplateA" +
                "ttributes_DynamicType\"><End Role=\"DynamicTemplateAttributes\" EntitySet=\"DynamicT" +
                "emplateAttributes\" /><End Role=\"DynamicType\" EntitySet=\"DynamicTypes\" /></Associ" +
                "ationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for DynamicModel.DynamicAttribute in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DynamicAttributes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DynamicAttribute : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DynamicAttribute object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicAttribute CreateDynamicAttribute(int ID, string name)
        {
            DynamicAttribute dynamicAttribute = new DynamicAttribute();
            dynamicAttribute.Id = ID;
            dynamicAttribute.Name = name;
            return dynamicAttribute;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute> DynamicTemplateAttributes
        {
            get
            {
                return this._DynamicTemplateAttributes;
            }
            set
            {
                this._DynamicTemplateAttributes = value;
                this.OnPropertyChanged("DynamicTemplateAttributes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute> _DynamicTemplateAttributes = new global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DynamicModel.DynamicTemplate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DynamicTemplates")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DynamicTemplate : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DynamicTemplate object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="description">Initial value of Description.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicTemplate CreateDynamicTemplate(int ID, string name, string description)
        {
            DynamicTemplate dynamicTemplate = new DynamicTemplate();
            dynamicTemplate.Id = ID;
            dynamicTemplate.Name = name;
            dynamicTemplate.Description = description;
            return dynamicTemplate;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute> DynamicTemplateAttributes
        {
            get
            {
                return this._DynamicTemplateAttributes;
            }
            set
            {
                this._DynamicTemplateAttributes = value;
                this.OnPropertyChanged("DynamicTemplateAttributes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute> _DynamicTemplateAttributes = new global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DynamicModel.DynamicTemplateAttribute in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AttributeId
    /// TemplateId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DynamicTemplateAttributes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AttributeId", "TemplateId")]
    public partial class DynamicTemplateAttribute : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DynamicTemplateAttribute object.
        /// </summary>
        /// <param name="templateId">Initial value of TemplateId.</param>
        /// <param name="attributeId">Initial value of AttributeId.</param>
        /// <param name="displayName">Initial value of DisplayName.</param>
        /// <param name="typeId">Initial value of TypeId.</param>
        /// <param name="idx">Initial value of Idx.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicTemplateAttribute CreateDynamicTemplateAttribute(int templateId, int attributeId, string displayName, int typeId, int idx)
        {
            DynamicTemplateAttribute dynamicTemplateAttribute = new DynamicTemplateAttribute();
            dynamicTemplateAttribute.TemplateId = templateId;
            dynamicTemplateAttribute.AttributeId = attributeId;
            dynamicTemplateAttribute.DisplayName = displayName;
            dynamicTemplateAttribute.TypeId = typeId;
            dynamicTemplateAttribute.Idx = idx;
            return dynamicTemplateAttribute;
        }
        /// <summary>
        /// There are no comments for Property TemplateId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TemplateId
        {
            get
            {
                return this._TemplateId;
            }
            set
            {
                this.OnTemplateIdChanging(value);
                this._TemplateId = value;
                this.OnTemplateIdChanged();
                this.OnPropertyChanged("TemplateId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TemplateId;
        partial void OnTemplateIdChanging(int value);
        partial void OnTemplateIdChanged();
        /// <summary>
        /// There are no comments for Property AttributeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AttributeId
        {
            get
            {
                return this._AttributeId;
            }
            set
            {
                this.OnAttributeIdChanging(value);
                this._AttributeId = value;
                this.OnAttributeIdChanged();
                this.OnPropertyChanged("AttributeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AttributeId;
        partial void OnAttributeIdChanging(int value);
        partial void OnAttributeIdChanged();
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
                this.OnPropertyChanged("DisplayName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property TypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TypeId
        {
            get
            {
                return this._TypeId;
            }
            set
            {
                this.OnTypeIdChanging(value);
                this._TypeId = value;
                this.OnTypeIdChanged();
                this.OnPropertyChanged("TypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TypeId;
        partial void OnTypeIdChanging(int value);
        partial void OnTypeIdChanged();
        /// <summary>
        /// There are no comments for Property Idx in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Idx
        {
            get
            {
                return this._Idx;
            }
            set
            {
                this.OnIdxChanging(value);
                this._Idx = value;
                this.OnIdxChanged();
                this.OnPropertyChanged("Idx");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Idx;
        partial void OnIdxChanging(int value);
        partial void OnIdxChanged();
        /// <summary>
        /// There are no comments for DynamicAttribute in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicAttribute DynamicAttribute
        {
            get
            {
                return this._DynamicAttribute;
            }
            set
            {
                this._DynamicAttribute = value;
                this.OnPropertyChanged("DynamicAttribute");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DynamicAttribute _DynamicAttribute;
        /// <summary>
        /// There are no comments for DynamicTemplate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicTemplate DynamicTemplate
        {
            get
            {
                return this._DynamicTemplate;
            }
            set
            {
                this._DynamicTemplate = value;
                this.OnPropertyChanged("DynamicTemplate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DynamicTemplate _DynamicTemplate;
        /// <summary>
        /// There are no comments for DynamicType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicType DynamicType
        {
            get
            {
                return this._DynamicType;
            }
            set
            {
                this._DynamicType = value;
                this.OnPropertyChanged("DynamicType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DynamicType _DynamicType;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DynamicModel.DynamicType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DynamicTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DynamicType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DynamicType object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicType CreateDynamicType(int ID, string name)
        {
            DynamicType dynamicType = new DynamicType();
            dynamicType.Id = ID;
            dynamicType.Name = name;
            return dynamicType;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for DynamicTemplateAttributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute> DynamicTemplateAttributes
        {
            get
            {
                return this._DynamicTemplateAttributes;
            }
            set
            {
                this._DynamicTemplateAttributes = value;
                this.OnPropertyChanged("DynamicTemplateAttributes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute> _DynamicTemplateAttributes = new global::System.Data.Services.Client.DataServiceCollection<DynamicTemplateAttribute>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
