//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//1) Open PowerShell
//2) Go to 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'
//3) Execute '.\DataSvcUtil.exe /out:D:\\dynamicmetadataservice.cs /uri:http://localhost/DynamicWebService/DynamicMetadataService.svc'
// Original file name: dynamicmetadataservice.cs
// Generation date: 6/14/2019 12:59:38 AM
namespace Web
{
    
    /// <summary>
    /// There are no comments for DynamicMetadataContext in the schema.
    /// </summary>
    public partial class DynamicMetadataContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DynamicMetadataContext object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicMetadataContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for DynamicFields in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicField> DynamicFields
        {
            get
            {
                if ((this._DynamicFields == null))
                {
                    this._DynamicFields = base.CreateQuery<DynamicField>("DynamicFields");
                }
                return this._DynamicFields;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicField> _DynamicFields;
        /// <summary>
        /// There are no comments for DynamicTemplates in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DynamicTemplate> DynamicTemplates
        {
            get
            {
                if ((this._DynamicTemplates == null))
                {
                    this._DynamicTemplates = base.CreateQuery<DynamicTemplate>("DynamicTemplates");
                }
                return this._DynamicTemplates;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DynamicTemplate> _DynamicTemplates;
        /// <summary>
        /// There are no comments for MenuItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MenuItem> MenuItems
        {
            get
            {
                if ((this._MenuItems == null))
                {
                    this._MenuItems = base.CreateQuery<MenuItem>("MenuItems");
                }
                return this._MenuItems;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MenuItem> _MenuItems;
        /// <summary>
        /// There are no comments for DynamicFields in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicFields(DynamicField dynamicField)
        {
            base.AddObject("DynamicFields", dynamicField);
        }
        /// <summary>
        /// There are no comments for DynamicTemplates in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDynamicTemplates(DynamicTemplate dynamicTemplate)
        {
            base.AddObject("DynamicTemplates", dynamicTemplate);
        }
        /// <summary>
        /// There are no comments for MenuItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMenuItems(MenuItem menuItem)
        {
            base.AddObject("MenuItems", menuItem);
        }
    }
    /// <summary>
    /// There are no comments for DynamicServerSide.Models.Metadata.DynamicField in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DynamicField
    {
        /// <summary>
        /// Create a new DynamicField object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isNullable">Initial value of IsNullable.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicField CreateDynamicField(int ID, bool isNullable)
        {
            DynamicField dynamicField = new DynamicField();
            dynamicField.Id = ID;
            dynamicField.IsNullable = isNullable;
            return dynamicField;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Label in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Label
        {
            get
            {
                return this._Label;
            }
            set
            {
                this.OnLabelChanging(value);
                this._Label = value;
                this.OnLabelChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Label;
        partial void OnLabelChanging(string value);
        partial void OnLabelChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ElementType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ElementType
        {
            get
            {
                return this._ElementType;
            }
            set
            {
                this.OnElementTypeChanging(value);
                this._ElementType = value;
                this.OnElementTypeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ElementType;
        partial void OnElementTypeChanging(string value);
        partial void OnElementTypeChanged();
        /// <summary>
        /// There are no comments for Property InputType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InputType
        {
            get
            {
                return this._InputType;
            }
            set
            {
                this.OnInputTypeChanging(value);
                this._InputType = value;
                this.OnInputTypeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InputType;
        partial void OnInputTypeChanging(string value);
        partial void OnInputTypeChanged();
        /// <summary>
        /// There are no comments for Property SqlTypeEnumCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> SqlTypeEnumCode
        {
            get
            {
                return this._SqlTypeEnumCode;
            }
            set
            {
                this.OnSqlTypeEnumCodeChanging(value);
                this._SqlTypeEnumCode = value;
                this.OnSqlTypeEnumCodeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _SqlTypeEnumCode;
        partial void OnSqlTypeEnumCodeChanging(global::System.Nullable<int> value);
        partial void OnSqlTypeEnumCodeChanged();
        /// <summary>
        /// There are no comments for Property IsNullable in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsNullable
        {
            get
            {
                return this._IsNullable;
            }
            set
            {
                this.OnIsNullableChanging(value);
                this._IsNullable = value;
                this.OnIsNullableChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsNullable;
        partial void OnIsNullableChanging(bool value);
        partial void OnIsNullableChanged();
        /// <summary>
        /// There are no comments for Property DefaultValue in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DefaultValue
        {
            get
            {
                return this._DefaultValue;
            }
            set
            {
                this.OnDefaultValueChanging(value);
                this._DefaultValue = value;
                this.OnDefaultValueChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DefaultValue;
        partial void OnDefaultValueChanging(string value);
        partial void OnDefaultValueChanged();
        /// <summary>
        /// There are no comments for Property OrderIndex in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> OrderIndex
        {
            get
            {
                return this._OrderIndex;
            }
            set
            {
                this.OnOrderIndexChanging(value);
                this._OrderIndex = value;
                this.OnOrderIndexChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _OrderIndex;
        partial void OnOrderIndexChanging(global::System.Nullable<int> value);
        partial void OnOrderIndexChanged();
        /// <summary>
        /// There are no comments for Property TemplateId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> TemplateId
        {
            get
            {
                return this._TemplateId;
            }
            set
            {
                this.OnTemplateIdChanging(value);
                this._TemplateId = value;
                this.OnTemplateIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _TemplateId;
        partial void OnTemplateIdChanging(global::System.Nullable<int> value);
        partial void OnTemplateIdChanged();
        /// <summary>
        /// There are no comments for Template in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DynamicTemplate Template
        {
            get
            {
                return this._Template;
            }
            set
            {
                this._Template = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DynamicTemplate _Template;
    }
    /// <summary>
    /// There are no comments for DynamicServerSide.Models.Metadata.DynamicTemplate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DynamicTemplate
    {
        /// <summary>
        /// Create a new DynamicTemplate object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isExist">Initial value of IsExist.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DynamicTemplate CreateDynamicTemplate(int ID, int isExist)
        {
            DynamicTemplate dynamicTemplate = new DynamicTemplate();
            dynamicTemplate.Id = ID;
            dynamicTemplate.IsExist = isExist;
            return dynamicTemplate;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsExist in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IsExist
        {
            get
            {
                return this._IsExist;
            }
            set
            {
                this.OnIsExistChanging(value);
                this._IsExist = value;
                this.OnIsExistChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IsExist;
        partial void OnIsExistChanging(int value);
        partial void OnIsExistChanged();
        /// <summary>
        /// There are no comments for DynamicFields in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<DynamicField> DynamicFields
        {
            get
            {
                return this._DynamicFields;
            }
            set
            {
                if ((value != null))
                {
                    this._DynamicFields = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<DynamicField> _DynamicFields = new global::System.Collections.ObjectModel.Collection<DynamicField>();
    }
    /// <summary>
    /// There are no comments for DynamicServerSide.Models.Metadata.MenuItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MenuItem
    {
        /// <summary>
        /// Create a new MenuItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MenuItem CreateMenuItem(int ID)
        {
            MenuItem menuItem = new MenuItem();
            menuItem.Id = ID;
            return menuItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property Route in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Route
        {
            get
            {
                return this._Route;
            }
            set
            {
                this.OnRouteChanging(value);
                this._Route = value;
                this.OnRouteChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Route;
        partial void OnRouteChanging(string value);
        partial void OnRouteChanged();
        /// <summary>
        /// There are no comments for Property IconName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IconName
        {
            get
            {
                return this._IconName;
            }
            set
            {
                this.OnIconNameChanging(value);
                this._IconName = value;
                this.OnIconNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IconName;
        partial void OnIconNameChanging(string value);
        partial void OnIconNameChanged();
        /// <summary>
        /// There are no comments for Property OrderIndex in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> OrderIndex
        {
            get
            {
                return this._OrderIndex;
            }
            set
            {
                this.OnOrderIndexChanging(value);
                this._OrderIndex = value;
                this.OnOrderIndexChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _OrderIndex;
        partial void OnOrderIndexChanging(global::System.Nullable<int> value);
        partial void OnOrderIndexChanged();
        /// <summary>
        /// There are no comments for Property ParentMenuItemId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ParentMenuItemId
        {
            get
            {
                return this._ParentMenuItemId;
            }
            set
            {
                this.OnParentMenuItemIdChanging(value);
                this._ParentMenuItemId = value;
                this.OnParentMenuItemIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ParentMenuItemId;
        partial void OnParentMenuItemIdChanging(global::System.Nullable<int> value);
        partial void OnParentMenuItemIdChanged();
        /// <summary>
        /// There are no comments for MenuItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<MenuItem> MenuItems
        {
            get
            {
                return this._MenuItems;
            }
            set
            {
                if ((value != null))
                {
                    this._MenuItems = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<MenuItem> _MenuItems = new global::System.Collections.ObjectModel.Collection<MenuItem>();
        /// <summary>
        /// There are no comments for ParentMenuItem in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MenuItem ParentMenuItem
        {
            get
            {
                return this._ParentMenuItem;
            }
            set
            {
                this._ParentMenuItem = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MenuItem _ParentMenuItem;
    }
}
