//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/22/2019 1:06:53 AM
namespace Web.OData.Models.Meta
{
    /// <summary>
    /// There are no comments for DynamicFieldSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicFieldSingle")]
    public partial class DynamicFieldSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DynamicField>
    {
        /// <summary>
        /// Initialize a new DynamicFieldSingle object.
        /// </summary>
        public DynamicFieldSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DynamicFieldSingle object.
        /// </summary>
        public DynamicFieldSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DynamicFieldSingle object.
        /// </summary>
        public DynamicFieldSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DynamicField> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Template in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Template")]
        public global::Web.OData.Models.Meta.DynamicTemplateSingle Template
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Template == null))
                {
                    this._Template = new global::Web.OData.Models.Meta.DynamicTemplateSingle(this.Context, GetPath("Template"));
                }
                return this._Template;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Web.OData.Models.Meta.DynamicTemplateSingle _Template;
    }
    /// <summary>
    /// There are no comments for DynamicField in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicField")]
    public partial class DynamicField : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DynamicField object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isNullable">Initial value of IsNullable.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static DynamicField CreateDynamicField(int ID, bool isNullable)
        {
            DynamicField dynamicField = new DynamicField();
            dynamicField.Id = ID;
            dynamicField.IsNullable = isNullable;
            return dynamicField;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Label in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Label")]
        public string Label
        {
            get
            {
                return this._Label;
            }
            set
            {
                this.OnLabelChanging(value);
                this._Label = value;
                this.OnLabelChanged();
                this.OnPropertyChanged("Label");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Label;
        partial void OnLabelChanging(string value);
        partial void OnLabelChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ElementType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ElementType")]
        public string ElementType
        {
            get
            {
                return this._ElementType;
            }
            set
            {
                this.OnElementTypeChanging(value);
                this._ElementType = value;
                this.OnElementTypeChanged();
                this.OnPropertyChanged("ElementType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _ElementType;
        partial void OnElementTypeChanging(string value);
        partial void OnElementTypeChanged();
        /// <summary>
        /// There are no comments for Property InputType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("InputType")]
        public string InputType
        {
            get
            {
                return this._InputType;
            }
            set
            {
                this.OnInputTypeChanging(value);
                this._InputType = value;
                this.OnInputTypeChanged();
                this.OnPropertyChanged("InputType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _InputType;
        partial void OnInputTypeChanging(string value);
        partial void OnInputTypeChanged();
        /// <summary>
        /// There are no comments for Property SqlTypeEnumCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SqlTypeEnumCode")]
        public global::System.Nullable<int> SqlTypeEnumCode
        {
            get
            {
                return this._SqlTypeEnumCode;
            }
            set
            {
                this.OnSqlTypeEnumCodeChanging(value);
                this._SqlTypeEnumCode = value;
                this.OnSqlTypeEnumCodeChanged();
                this.OnPropertyChanged("SqlTypeEnumCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _SqlTypeEnumCode;
        partial void OnSqlTypeEnumCodeChanging(global::System.Nullable<int> value);
        partial void OnSqlTypeEnumCodeChanged();
        /// <summary>
        /// There are no comments for Property IsNullable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsNullable")]
        public bool IsNullable
        {
            get
            {
                return this._IsNullable;
            }
            set
            {
                this.OnIsNullableChanging(value);
                this._IsNullable = value;
                this.OnIsNullableChanged();
                this.OnPropertyChanged("IsNullable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _IsNullable;
        partial void OnIsNullableChanging(bool value);
        partial void OnIsNullableChanged();
        /// <summary>
        /// There are no comments for Property DefaultValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DefaultValue")]
        public string DefaultValue
        {
            get
            {
                return this._DefaultValue;
            }
            set
            {
                this.OnDefaultValueChanging(value);
                this._DefaultValue = value;
                this.OnDefaultValueChanged();
                this.OnPropertyChanged("DefaultValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _DefaultValue;
        partial void OnDefaultValueChanging(string value);
        partial void OnDefaultValueChanged();
        /// <summary>
        /// There are no comments for Property OrderIndex in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OrderIndex")]
        public global::System.Nullable<int> OrderIndex
        {
            get
            {
                return this._OrderIndex;
            }
            set
            {
                this.OnOrderIndexChanging(value);
                this._OrderIndex = value;
                this.OnOrderIndexChanged();
                this.OnPropertyChanged("OrderIndex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _OrderIndex;
        partial void OnOrderIndexChanging(global::System.Nullable<int> value);
        partial void OnOrderIndexChanged();
        /// <summary>
        /// There are no comments for Property TemplateId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TemplateId")]
        public global::System.Nullable<int> TemplateId
        {
            get
            {
                return this._TemplateId;
            }
            set
            {
                this.OnTemplateIdChanging(value);
                this._TemplateId = value;
                this.OnTemplateIdChanged();
                this.OnPropertyChanged("TemplateId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _TemplateId;
        partial void OnTemplateIdChanging(global::System.Nullable<int> value);
        partial void OnTemplateIdChanged();
        /// <summary>
        /// There are no comments for Property Template in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Template")]
        public global::Web.OData.Models.Meta.DynamicTemplate Template
        {
            get
            {
                return this._Template;
            }
            set
            {
                this.OnTemplateChanging(value);
                this._Template = value;
                this.OnTemplateChanged();
                this.OnPropertyChanged("Template");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Web.OData.Models.Meta.DynamicTemplate _Template;
        partial void OnTemplateChanging(global::Web.OData.Models.Meta.DynamicTemplate value);
        partial void OnTemplateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DynamicTemplateSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicTemplateSingle")]
    public partial class DynamicTemplateSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DynamicTemplate>
    {
        /// <summary>
        /// Initialize a new DynamicTemplateSingle object.
        /// </summary>
        public DynamicTemplateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DynamicTemplateSingle object.
        /// </summary>
        public DynamicTemplateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DynamicTemplateSingle object.
        /// </summary>
        public DynamicTemplateSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DynamicTemplate> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for DynamicFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicFields")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicField> DynamicFields
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._DynamicFields == null))
                {
                    this._DynamicFields = Context.CreateQuery<global::Web.OData.Models.Meta.DynamicField>(GetPath("DynamicFields"));
                }
                return this._DynamicFields;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicField> _DynamicFields;
    }
    /// <summary>
    /// There are no comments for DynamicTemplate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicTemplate")]
    public partial class DynamicTemplate : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DynamicTemplate object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isExist">Initial value of IsExist.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static DynamicTemplate CreateDynamicTemplate(int ID, int isExist)
        {
            DynamicTemplate dynamicTemplate = new DynamicTemplate();
            dynamicTemplate.Id = ID;
            dynamicTemplate.IsExist = isExist;
            return dynamicTemplate;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsExist in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsExist")]
        public int IsExist
        {
            get
            {
                return this._IsExist;
            }
            set
            {
                this.OnIsExistChanging(value);
                this._IsExist = value;
                this.OnIsExistChanged();
                this.OnPropertyChanged("IsExist");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _IsExist;
        partial void OnIsExistChanging(int value);
        partial void OnIsExistChanged();
        /// <summary>
        /// There are no comments for Property DynamicFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicFields")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Web.OData.Models.Meta.DynamicField> DynamicFields
        {
            get
            {
                return this._DynamicFields;
            }
            set
            {
                this.OnDynamicFieldsChanging(value);
                this._DynamicFields = value;
                this.OnDynamicFieldsChanged();
                this.OnPropertyChanged("DynamicFields");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Web.OData.Models.Meta.DynamicField> _DynamicFields = new global::Microsoft.OData.Client.DataServiceCollection<global::Web.OData.Models.Meta.DynamicField>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnDynamicFieldsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Web.OData.Models.Meta.DynamicField> value);
        partial void OnDynamicFieldsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MenuItemSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MenuItemSingle")]
    public partial class MenuItemSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<MenuItem>
    {
        /// <summary>
        /// Initialize a new MenuItemSingle object.
        /// </summary>
        public MenuItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MenuItemSingle object.
        /// </summary>
        public MenuItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MenuItemSingle object.
        /// </summary>
        public MenuItemSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<MenuItem> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for ParentMenuItem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ParentMenuItem")]
        public global::Web.OData.Models.Meta.MenuItemSingle ParentMenuItem
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentMenuItem == null))
                {
                    this._ParentMenuItem = new global::Web.OData.Models.Meta.MenuItemSingle(this.Context, GetPath("ParentMenuItem"));
                }
                return this._ParentMenuItem;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Web.OData.Models.Meta.MenuItemSingle _ParentMenuItem;
        /// <summary>
        /// There are no comments for MenuItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MenuItems")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.MenuItem> MenuItems
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._MenuItems == null))
                {
                    this._MenuItems = Context.CreateQuery<global::Web.OData.Models.Meta.MenuItem>(GetPath("MenuItems"));
                }
                return this._MenuItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.MenuItem> _MenuItems;
    }
    /// <summary>
    /// There are no comments for MenuItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("MenuItem")]
    public partial class MenuItem : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MenuItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static MenuItem CreateMenuItem(int ID)
        {
            MenuItem menuItem = new MenuItem();
            menuItem.Id = ID;
            return menuItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DisplayName")]
        public string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
                this.OnPropertyChanged("DisplayName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property Route in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Route")]
        public string Route
        {
            get
            {
                return this._Route;
            }
            set
            {
                this.OnRouteChanging(value);
                this._Route = value;
                this.OnRouteChanged();
                this.OnPropertyChanged("Route");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Route;
        partial void OnRouteChanging(string value);
        partial void OnRouteChanged();
        /// <summary>
        /// There are no comments for Property IconName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IconName")]
        public string IconName
        {
            get
            {
                return this._IconName;
            }
            set
            {
                this.OnIconNameChanging(value);
                this._IconName = value;
                this.OnIconNameChanged();
                this.OnPropertyChanged("IconName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _IconName;
        partial void OnIconNameChanging(string value);
        partial void OnIconNameChanged();
        /// <summary>
        /// There are no comments for Property OrderIndex in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OrderIndex")]
        public global::System.Nullable<int> OrderIndex
        {
            get
            {
                return this._OrderIndex;
            }
            set
            {
                this.OnOrderIndexChanging(value);
                this._OrderIndex = value;
                this.OnOrderIndexChanged();
                this.OnPropertyChanged("OrderIndex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _OrderIndex;
        partial void OnOrderIndexChanging(global::System.Nullable<int> value);
        partial void OnOrderIndexChanged();
        /// <summary>
        /// There are no comments for Property ParentMenuItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ParentMenuItemId")]
        public global::System.Nullable<int> ParentMenuItemId
        {
            get
            {
                return this._ParentMenuItemId;
            }
            set
            {
                this.OnParentMenuItemIdChanging(value);
                this._ParentMenuItemId = value;
                this.OnParentMenuItemIdChanged();
                this.OnPropertyChanged("ParentMenuItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _ParentMenuItemId;
        partial void OnParentMenuItemIdChanging(global::System.Nullable<int> value);
        partial void OnParentMenuItemIdChanged();
        /// <summary>
        /// There are no comments for Property ParentMenuItem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ParentMenuItem")]
        public global::Web.OData.Models.Meta.MenuItem ParentMenuItem
        {
            get
            {
                return this._ParentMenuItem;
            }
            set
            {
                this.OnParentMenuItemChanging(value);
                this._ParentMenuItem = value;
                this.OnParentMenuItemChanged();
                this.OnPropertyChanged("ParentMenuItem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Web.OData.Models.Meta.MenuItem _ParentMenuItem;
        partial void OnParentMenuItemChanging(global::Web.OData.Models.Meta.MenuItem value);
        partial void OnParentMenuItemChanged();
        /// <summary>
        /// There are no comments for Property MenuItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MenuItems")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Web.OData.Models.Meta.MenuItem> MenuItems
        {
            get
            {
                return this._MenuItems;
            }
            set
            {
                this.OnMenuItemsChanging(value);
                this._MenuItems = value;
                this.OnMenuItemsChanged();
                this.OnPropertyChanged("MenuItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Web.OData.Models.Meta.MenuItem> _MenuItems = new global::Microsoft.OData.Client.DataServiceCollection<global::Web.OData.Models.Meta.MenuItem>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnMenuItemsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Web.OData.Models.Meta.MenuItem> value);
        partial void OnMenuItemsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Web.OData.Models.Meta.DynamicField as global::Web.OData.Models.Meta.DynamicFieldSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Web.OData.Models.Meta.DynamicFieldSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicField> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Web.OData.Models.Meta.DynamicFieldSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Web.OData.Models.Meta.DynamicField as global::Web.OData.Models.Meta.DynamicFieldSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Web.OData.Models.Meta.DynamicFieldSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicField> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Web.OData.Models.Meta.DynamicFieldSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Web.OData.Models.Meta.DynamicTemplate as global::Web.OData.Models.Meta.DynamicTemplateSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Web.OData.Models.Meta.DynamicTemplateSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicTemplate> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Web.OData.Models.Meta.DynamicTemplateSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Web.OData.Models.Meta.DynamicTemplate as global::Web.OData.Models.Meta.DynamicTemplateSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Web.OData.Models.Meta.DynamicTemplateSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicTemplate> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Web.OData.Models.Meta.DynamicTemplateSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Web.OData.Models.Meta.MenuItem as global::Web.OData.Models.Meta.MenuItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Web.OData.Models.Meta.MenuItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.MenuItem> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Web.OData.Models.Meta.MenuItemSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Web.OData.Models.Meta.MenuItem as global::Web.OData.Models.Meta.MenuItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Web.OData.Models.Meta.MenuItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.MenuItem> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Web.OData.Models.Meta.MenuItemSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Web.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "OData.Models.Meta", "Web.OData.Models.Meta");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Web.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Web.OData.Models.Meta", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("OData.Models.Meta.", originalNameAttribute.OriginalName);
                }
                return string.Concat("OData.Models.Meta.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Web.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for DynamicFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicFields")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicField> DynamicFields
        {
            get
            {
                if ((this._DynamicFields == null))
                {
                    this._DynamicFields = base.CreateQuery<global::Web.OData.Models.Meta.DynamicField>("DynamicFields");
                }
                return this._DynamicFields;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicField> _DynamicFields;
        /// <summary>
        /// There are no comments for DynamicTemplates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicTemplates")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicTemplate> DynamicTemplates
        {
            get
            {
                if ((this._DynamicTemplates == null))
                {
                    this._DynamicTemplates = base.CreateQuery<global::Web.OData.Models.Meta.DynamicTemplate>("DynamicTemplates");
                }
                return this._DynamicTemplates;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.DynamicTemplate> _DynamicTemplates;
        /// <summary>
        /// There are no comments for MenuItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MenuItems")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.MenuItem> MenuItems
        {
            get
            {
                if ((this._MenuItems == null))
                {
                    this._MenuItems = base.CreateQuery<global::Web.OData.Models.Meta.MenuItem>("MenuItems");
                }
                return this._MenuItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Web.OData.Models.Meta.MenuItem> _MenuItems;
        /// <summary>
        /// There are no comments for DynamicFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToDynamicFields(global::Web.OData.Models.Meta.DynamicField dynamicField)
        {
            base.AddObject("DynamicFields", dynamicField);
        }
        /// <summary>
        /// There are no comments for DynamicTemplates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToDynamicTemplates(global::Web.OData.Models.Meta.DynamicTemplate dynamicTemplate)
        {
            base.AddObject("DynamicTemplates", dynamicTemplate);
        }
        /// <summary>
        /// There are no comments for MenuItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToMenuItems(global::Web.OData.Models.Meta.MenuItem menuItem)
        {
            base.AddObject("MenuItems", menuItem);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""OData.Models.Meta"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""DynamicField"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Label"" Type=""Edm.String"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""ElementType"" Type=""Edm.String"" />
        <Property Name=""InputType"" Type=""Edm.String"" />
        <Property Name=""SqlTypeEnumCode"" Type=""Edm.Int32"" />
        <Property Name=""IsNullable"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""DefaultValue"" Type=""Edm.String"" />
        <Property Name=""OrderIndex"" Type=""Edm.Int32"" />
        <Property Name=""TemplateId"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Template"" Type=""OData.Models.Meta.DynamicTemplate"">
          <ReferentialConstraint Property=""TemplateId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""DynamicTemplate"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <Property Name=""IsExist"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""DynamicFields"" Type=""Collection(OData.Models.Meta.DynamicField)"" />
      </EntityType>
      <EntityType Name=""MenuItem"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""DisplayName"" Type=""Edm.String"" />
        <Property Name=""Route"" Type=""Edm.String"" />
        <Property Name=""IconName"" Type=""Edm.String"" />
        <Property Name=""OrderIndex"" Type=""Edm.Int32"" />
        <Property Name=""ParentMenuItemId"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""ParentMenuItem"" Type=""OData.Models.Meta.MenuItem"">
          <ReferentialConstraint Property=""ParentMenuItemId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""MenuItems"" Type=""Collection(OData.Models.Meta.MenuItem)"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""DynamicFields"" EntityType=""OData.Models.Meta.DynamicField"">
          <NavigationPropertyBinding Path=""Template"" Target=""DynamicTemplates"" />
        </EntitySet>
        <EntitySet Name=""DynamicTemplates"" EntityType=""OData.Models.Meta.DynamicTemplate"">
          <NavigationPropertyBinding Path=""DynamicFields"" Target=""DynamicFields"" />
        </EntitySet>
        <EntitySet Name=""MenuItems"" EntityType=""OData.Models.Meta.MenuItem"">
          <NavigationPropertyBinding Path=""ParentMenuItem"" Target=""MenuItems"" />
          <NavigationPropertyBinding Path=""MenuItems"" Target=""MenuItems"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
